### ISSUE TITLE
Not compatible with libGeos.jl@0.7.0

### ISSUE THREAD

**Issue by Song921012** [RafaelArutjunjan/InformationGeometry.jl#43]
Hello, thank you for your excellent work. `InformationGeometry` include compat for `libGeos.jl@0.7.0`. However, `libGeos.jl` has changes may break  `InformationGeometry` . `AbstractPolygon` was removed in `libGeos.jl` but used in `InformationGeometry`.

**Comment by RafaelArutjunjan** [comment]
Hello there. Thanks for informing me - this issue is fixed in the upcoming version v1.13.2 which should be merged into the Julia registries within the next couple of hours.
